--DATA PREPARATION AND UNDERSTANDING 

--1. What is the total number of rows in each of the 3 tables in the database?

select count(*) from Customer
select count(*) from prod_cat_info
select count(*) from Transactions

--2. What is the total number of transactions that have a return? 

select count(Qty) as count_of_return_transactions
from Transactions
where Qty<0

/*3. As you would have noticed, the dates provided across the datasets are not in a 
correct format. As first steps, pls convert the date variables into valid date formats 
before proceeding ahead. */

select FORMAT(tran_date,'dd-mm-yyyy') as formatted_Trans_Date
from Transactions	
select * from Transactions

--4.What is the time range of the transaction data available for analysis? Show the 
--output in number of days, months and years simultaneously in different columns. 
select 
      DATEDIFF(DAY,min(tran_date),max(tran_date)) as days,
	  datediff(month,min(tran_date),max(tran_date)) as months,
	  DATEDIFF(year,min(tran_date),max(tran_date)) as years
from Transactions

--5. Which product category does the sub-category “DIY” belong to? 
select prod_cat,
       prod_subcat
from prod_cat_info
where prod_subcat='DIY'

--dataAnalysis

--1. Which channel is most frequently used for transactions? 
select top 1 Store_type,
       count(Store_type) as count_of_chanel
from Transactions
group by Store_type
order by count_of_chanel desc

--2. What is the count of Male and Female customers in the database? 
select count(Gender) as count_of_male
from Customer
where Gender='M' 

select count(Gender) as count_of_Female
from Customer
where Gender='F' 

--3. From which city do we have the maximum number of customers and how many? 
select top 1 count(customer_Id) as count_of_customers,
       city_code
from Customer
group by city_code
order by count_of_customers desc

--4. How many sub-categories are there under the Books category? 
select prod_cat,
       count(prod_subcat) as count_of_subcategoory
from prod_cat_info
where prod_cat='Books'
group by prod_cat

--5. What is the maximum quantity of products ever ordered? 
select max(Qty) as max_qty
from Transactions

--6. What is the net total revenue generated in categories Electronics and Books?
select prod_cat,
       sum(total_amt) as revenue
from Transactions t
join prod_cat_info p on t.prod_cat_code=p.prod_cat_code
where prod_cat='Electronics' or prod_cat='Books'
group by prod_cat

--7. How many customers have >10 transactions with us, excluding returns? 
select count(*) as count_of_customers
from
(select cust_id
from Transactions
where Qty>0
group by cust_id
having   count(transaction_id)>10)as t

--8. What is the combined revenue earned from the “Electronics” & “Clothing” 
--categories, from “Flagship stores”? 
select sum(total_amt) as total_amt
from Transactions t
join prod_cat_info p on t.prod_cat_code=p.prod_cat_code
where Store_type='Flagship store' and (prod_cat='Electronics' or prod_cat='Clothing')

--9. What is the total revenue generated from “Male” customers in “Electronics” 
--category? Output should display total revenue by prod sub-cat. 
select p.prod_subcat,sum(t.total_amt) as revenue
from Customer c 
join Transactions t on c.customer_Id=t.cust_id
join prod_cat_info p on p.prod_cat_code=t.prod_cat_code
and p.prod_sub_cat_code=t.prod_subcat_code
where Gender='M' and prod_cat='Electronics'
group by p.prod_subcat

--10.What is percentage of sales and returns by product sub category; display only top 
--5 sub categories in terms of sales? 
select prod_subcat,
       sum(case when Qty>0 then total_amt else 0 end) as total_sales,
	   sum(case when Qty<0 then total_amt else 0 end) as total_returns
	  
from Transactions t
join prod_cat_info p on p.prod_sub_cat_code=t.prod_subcat_code
group by prod_subcat



/*11. For all customers aged between 25 to 35 years find what is the net total revenue 
generated by these consumers in last 30 days of transactions from max transaction 
date available in the data?*/

select customer_Id,
      sum(total_amt-Tax) as revenue
from Customer c
join Transactions t on t.cust_id=c.customer_Id
where  DATEDIFF(YEAR,DOB,(select max(tran_date)from Transactions)) between 25 and 35
and t.tran_date > DATEADD(day,-30,(select max(tran_date) from Transactions))
and Qty>0
group by customer_Id

--12.Which product category has seen the max value of returns in the last 3 months of 
--transactions? 
select top 1 prod_cat,
	   sum(Qty) as maxreturn
from Transactions t 
join prod_cat_info p on p.prod_cat_code=t.prod_cat_code
and  p.prod_sub_cat_code=t.prod_subcat_code
where Qty<0
and t.tran_date> DATEADD(MONTH,-3,(select max(tran_date) from Transactions))
group by prod_cat 
order by maxreturn asc

--13.Which store-type sells the maximum products; by value of sales amount and by 
--quantity sold? 
select top 1 Store_type,
       sum(Qty) as qty,
	   sum(total_amt) as salesamount
from Transactions
group by Store_type
order by salesamount desc,qty desc

--14.What are the categories for which average revenue is above the overall average. 
select prod_cat_code,
       avg(total_amt) avg_revenue
from Transactions
group by prod_cat_code
having avg(total_amt)>(select avg(total_amt) from Transactions)

--15. Find the average and total revenue by each subcategory for the categories which 
--are among top 5 categories in terms of quantity sold.
with topproducts as 
(select top 5 prod_cat_code,
       sum(Qty) as qty
from Transactions
group by prod_cat_code
order by qty desc)

select prod_subcat_code,
       sum(total_amt) as totalrevenue,
	   AVG(total_amt) as avgrevenue
from Transactions t
join topproducts tp on tp.prod_cat_code=t.prod_cat_code
group by t.prod_subcat_code






